---

- name: install python kubernetes core pre-requisites
  pip:
    name:
      - pyyaml
      - kubernetes
      - jsonpatch

- name: Deploy Service Account with role and rolebinding to manage Cluster's nodes.
  kubernetes.core.k8s:
    state: present
    template:
      - path: '../templates/serviceaccount.yml.j2'

- name: Get Service Account detail
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ServiceAccount
    name: manage-node
    namespace: kube-system
  register: sa_manage_node

- name: Get Secret detail
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ sa_manage_node['resources'][0]['secrets'][0]['name'] }}"
    namespace: kube-system
  register: sa_manage_node_secrets

- name: "Add K8S Token and Hash to dummy host"
  add_host:
    name:   "K8S_TOKEN_HOLDER"
    hash: "K8S_TOKEN_HOLDER"
    token:  "{{ sa_manage_node_secrets['resources'][0]['data']['token'] | b64decode }}"
    ca:     "{{ sa_manage_node_secrets['resources'][0]['data']['ca.crt'] | b64decode }}"
